### ISSUE TITLE
Getting "unhashable type: 'list'" error when cluster_on_key_properties is enabled

### ISSUE THREAD

**Issue by pep4eto1211** [z3z1ma/target-bigquery#41]
Description of problem:
I am running the tap using Meltano.
I have a simple setup where I try to load data from the [pipelinewise-tap-mysql](https://github.com/transferwise/pipelinewise-tap-mysql) tap. As the catalog file, generated by the tap is quite large (> 17 MB) and I only need a single table, I am setting the selected streams and the stream metadata using the Meltano config file. Below is sample configuration for the source:
```yaml
- name: tap-mysql
    variant: transferwise
    pip_url: pipelinewise-tap-mysql
    config:
      host: mysql.host.com
      port: 3306
      database: database_name
    select:
    - database_name-TableName.primaryKeyColumn
    - database_name-TableName.lastModified
    - database_name-TableName.textColumn
    metadata: 
      database_name-TableName:
        table-key-properties: ["primaryKeyColumn"]
        replication-method: INCREMENTAL
        replication-key: last_modified
```

The `target-bigquery` tap is configered like this:
```yaml
      project: gcp-project-id
      dataset: dataset_name
      batch_size: 100000
      denormalized: true
      method: batch_job
      upsert: true
      cluster_on_key_properties: true
      partition_granularity: day
      column_name_transforms:
        add_underscore_when_invalid: true
      schema_resolver_version: 2
```

When I try to run a pipeline I get the following error:
```
Traceback (most recent call last): 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/bin/target-bigquery", line 8, in <module> 
    sys.exit(TargetBigQuery.cli()) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__ 
    return self.main(*args, **kwargs) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main 
    rv = self.invoke(ctx)      
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke 
    return __callback(*args, **kwargs) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 578, in cli 
    target.listen(file_input)  
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 34, in listen 
    self._process_lines(file_input) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 278, in _process_lines 
    counter = super()._process_lines(file_input) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 78, in _process_lines 
    self._process_schema_message(line_dict) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 378, in _process_schema_message 
    _ = self.get_sink(         
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/target.py", line 482, in get_sink 
    return self.add_sink(stream_name, schema, key_properties) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 240, in add_sink 
    sink = sink_class(         
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/batch_job.py", line 101, in __init__ 
    super().__init__(*args, **kwargs) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/core.py", line 303, in __init__ 
    self.create_target(key_properties=key_properties) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f 
    return self(f, *args, **kw) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__ 
    do = self.iter(retry_state=retry_state) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter 
    return fut.result()        
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result 
    return self.__get_result() 
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result 
    raise self._exception      
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__ 
    result = fn(*args, **kwargs) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/core.py", line 469, in create_target 
    self.table.create_table(self.client, self.apply_transforms, **kwargs) 
  File "/home/source/pipeline/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/core.py", line 185, in create_table 
    self.as_table(             
TypeError: unhashable type: 'list' 
Loading failed
```

This error happens when the `cluster_on_key_properties` property is set to true. Running the target with this property set to `false` was successful.

**Comment by alexesDev** [comment]
Need change this line: https://github.com/z3z1ma/target-bigquery/blob/faddcfc12be9e1929cdd4816869e229c56431dff/target_bigquery/core.py#L456
to
```python
kwargs["table"]["clustering_fields"] = tuple(key_properties[:4])
```
It's a problem with `@cache`
